[package]
name = "acray"
version = "0.1.0"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
edition = "2018"

[features]
default = [ "simple_logger" ]

[dependencies]
rand = "~0.7.3"
log = "~0.4.8"
simple_logger = { version = "~1.4.0", optional = true }
